// ============================================================================
// StepChat — 단계별 Claude 미세조정 (키프레임부터 구현)
// ----------------------------------------------------------------------------
// 사용자 자연어 수정 요청 → Claude 가 그 단계의 파라미터(키프레임은 style bible)를
// 갱신 → 호출부가 저장하고 해당 단계 재생성. 다른 단계도 같은 패턴으로 확장.
// ============================================================================

import { getAnthropic, MODELS } from "./anthropic";
import { anthropicCostUsd, recordCost } from "./cost";

function parseJson(raw: string): { reply?: unknown; style_bible?: unknown } | null {
  const m = raw.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]);
  } catch {
    return null;
  }
}

// 키프레임 StepChat: style bible 을 사용자 요청대로 다듬는다.
export async function runKeyframeChat(args: {
  projectId: string;
  styleProfileLabel: string;
  currentStyleBible: string;
  userMessage: string;
}): Promise<{ reply: string; styleBible: string; costUsd: number }> {
  const { projectId, styleProfileLabel, currentStyleBible, userMessage } = args;
  const client = getAnthropic();

  const system =
    `You refine the visual STYLE BIBLE for a short-form (9:16 vertical) video keyframe ` +
    `generated by gpt-image-2. Style profile: "${styleProfileLabel}". The style bible is ` +
    `the English text that locks the art style, character design, color palette and ` +
    `composition for the whole video. Given the user's adjustment request (Korean), output ` +
    `an UPDATED style bible (English, concise, concrete, keep what the user didn't ask to ` +
    `change) and a short Korean reply summarizing what changed. Keep it 9:16 vertical and ` +
    `consistent with the profile. Return ONLY JSON: {"reply":"...","style_bible":"..."}`;

  const userMsg =
    `현재 style bible:\n${currentStyleBible}\n\n수정 요청: ${userMessage}`;

  const r = await client.messages.create({
    model: MODELS.sonnet,
    max_tokens: 1500,
    system,
    messages: [{ role: "user", content: userMsg }],
  });

  const textBlocks = r.content.filter(
    (b: { type: string }) => b.type === "text"
  ) as Array<{ type: "text"; text: string }>;
  const raw = textBlocks.map((b) => b.text).join("").trim();

  const costUsd = anthropicCostUsd({
    inputTokens: r.usage.input_tokens,
    outputTokens: r.usage.output_tokens,
    cacheReadTokens: r.usage.cache_read_input_tokens ?? undefined,
    cacheWriteTokens: r.usage.cache_creation_input_tokens ?? undefined,
    model: MODELS.sonnet,
  });
  await recordCost({
    projectId,
    vendor: "anthropic",
    model: MODELS.sonnet,
    costUsd,
    meta: { kind: "stepchat-keyframe" },
  });

  const parsed = parseJson(raw);
  const styleBible =
    parsed && typeof parsed.style_bible === "string" && parsed.style_bible.trim()
      ? parsed.style_bible.trim()
      : currentStyleBible; // 파싱 실패 시 기존 유지
  const reply =
    parsed && typeof parsed.reply === "string" && parsed.reply.trim()
      ? parsed.reply.trim()
      : "스타일을 갱신했어요.";

  return { reply, styleBible, costUsd };
}
