// ============================================================================
// StepChat — 단계별 Claude 미세조정 (키프레임부터 구현)
// ----------------------------------------------------------------------------
// 사용자 자연어 수정 요청 → Claude 가 그 단계의 파라미터(키프레임은 style bible)를
// 갱신 → 호출부가 저장하고 해당 단계 재생성. 다른 단계도 같은 패턴으로 확장.
// ============================================================================

import { getAnthropic, MODELS } from "./anthropic";
import { anthropicCostUsd, recordCost } from "./cost";
import type { SourceMaterial } from "./source";

// ── 팩트체크 (2단계) — 씬 나레이션의 사실관계를 검증한다 ─────────────────────────
// 소스 본문을 근거로, 스크립트가 소스를 왜곡·과장·오류 없이 담았는지 + 일반 상식/
// 알려진 사실과 어긋나는 곳이 없는지 씬 번호별로 지적한다. 씬을 고치지는 않고(리포트만),
// 고치기는 대화창에서 runScriptChat 으로 이어간다. 양질 모델(opus).
export async function runFactCheck(args: {
  projectId: string;
  narrations: string[];
  material?: SourceMaterial;
}): Promise<{ reply: string; costUsd: number }> {
  const { projectId, narrations, material } = args;
  const client = getAnthropic();

  const system =
    "You are a fact-checker for a short-form Korean news video script. You are given the SOURCE material " +
    "(the ground-truth article, Korean) and the SCRIPT as a numbered list of scene narrations (Korean). " +
    "Check each scene for: (1) claims that contradict or distort the source, (2) exaggerations, numbers, " +
    "dates, names or quotes that don't match the source, (3) statements that are factually wrong or misleading " +
    "against well-known facts, (4) missing critical context that makes a scene misleading. " +
    "Reply in KOREAN as a concise, scannable report: for each problem, cite the scene number (씬 N), quote the " +
    "issue briefly, explain why, and suggest the fix. If a scene is fine, don't list it. If the whole script is " +
    "accurate, say so clearly. End with one line telling the user they can ask you to apply any fix in this chat. " +
    "Do NOT rewrite the whole script here — this is a review, not an edit. Plain text, no JSON, no markdown headers.";

  const userMsg =
    (material
      ? `소스 제목: ${material.title}\n\n소스 본문(사실 근거):\n${material.body}\n\n`
      : "(소스 본문 없음 — 일반 상식·알려진 사실 기준으로만 검증)\n\n") +
    "스크립트 씬 나레이션:\n" +
    narrations.map((n, i) => `${i + 1}. ${n}`).join("\n");

  const r = await client.messages.create({
    model: MODELS.opus,
    max_tokens: 4000,
    system,
    messages: [{ role: "user", content: userMsg }],
  });

  const raw = textOf(r.content);
  const costUsd = anthropicCostUsd({
    inputTokens: r.usage.input_tokens,
    outputTokens: r.usage.output_tokens,
    cacheReadTokens: r.usage.cache_read_input_tokens ?? undefined,
    cacheWriteTokens: r.usage.cache_creation_input_tokens ?? undefined,
    model: MODELS.opus,
  });
  await recordCost({
    projectId,
    vendor: "anthropic",
    model: MODELS.opus,
    costUsd,
    meta: { kind: "factcheck" },
  }).catch(() => {});

  const reply = raw || "팩트체크 결과를 받지 못했어요 — 다시 시도해 주세요.";
  return { reply, costUsd };
}

function parseJson(raw: string): { reply?: unknown; style_bible?: unknown } | null {
  const m = raw.match(/\{[\s\S]*\}/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]);
  } catch {
    return null;
  }
}

// 키프레임 StepChat: style bible 을 사용자 요청대로 다듬는다.
export async function runKeyframeChat(args: {
  projectId: string;
  styleProfileLabel: string;
  currentStyleBible: string;
  userMessage: string;
}): Promise<{ reply: string; styleBible: string; costUsd: number }> {
  const { projectId, styleProfileLabel, currentStyleBible, userMessage } = args;
  const client = getAnthropic();

  const system =
    `You refine the visual STYLE BIBLE for a short-form (9:16 vertical) video keyframe ` +
    `generated by gpt-image-2. Style profile: "${styleProfileLabel}". The style bible is ` +
    `the English text that locks the art style, character design, color palette and ` +
    `composition for the whole video. Given the user's adjustment request (Korean), output ` +
    `an UPDATED style bible (English, concise, concrete, keep what the user didn't ask to ` +
    `change) and a short Korean reply summarizing what changed. Keep it 9:16 vertical and ` +
    `consistent with the profile. Return ONLY JSON: {"reply":"...","style_bible":"..."}`;

  const userMsg =
    `현재 style bible:\n${currentStyleBible}\n\n수정 요청: ${userMessage}`;

  const r = await client.messages.create({
    model: MODELS.sonnet,
    max_tokens: 1500,
    system,
    messages: [{ role: "user", content: userMsg }],
  });

  const textBlocks = r.content.filter(
    (b: { type: string }) => b.type === "text"
  ) as Array<{ type: "text"; text: string }>;
  const raw = textBlocks.map((b) => b.text).join("").trim();

  const costUsd = anthropicCostUsd({
    inputTokens: r.usage.input_tokens,
    outputTokens: r.usage.output_tokens,
    cacheReadTokens: r.usage.cache_read_input_tokens ?? undefined,
    cacheWriteTokens: r.usage.cache_creation_input_tokens ?? undefined,
    model: MODELS.sonnet,
  });
  await recordCost({
    projectId,
    vendor: "anthropic",
    model: MODELS.sonnet,
    costUsd,
    meta: { kind: "stepchat-keyframe" },
  });

  const parsed = parseJson(raw);
  const styleBible =
    parsed && typeof parsed.style_bible === "string" && parsed.style_bible.trim()
      ? parsed.style_bible.trim()
      : currentStyleBible; // 파싱 실패 시 기존 유지
  const reply =
    parsed && typeof parsed.reply === "string" && parsed.reply.trim()
      ? parsed.reply.trim()
      : "스타일을 갱신했어요.";

  return { reply, styleBible, costUsd };
}

// 1단계 소스 대화 — 사용자 요청대로 소스 자료(제목·본문)를 다듬는다. 강조·재작성·복수
// 소스 조합·톤/길이 조정 등. 좋은 모델(opus)로 양질의 컨텐츠를 뽑는다. 현재 자료를 항상
// 최신 상태로 넘기고, 갱신된 자료 + 한국어 요약 답변을 돌려준다.
function textOf(content: Array<{ type: string; text?: string }>): string {
  return (content.filter((b) => b.type === "text") as Array<{ text: string }>)
    .map((b) => b.text)
    .join("")
    .trim();
}

export async function runSourceChat(args: {
  projectId: string;
  material: SourceMaterial;
  userMessage: string;
}): Promise<{ reply: string; material: SourceMaterial; costUsd: number }> {
  const { projectId, material, userMessage } = args;
  const client = getAnthropic();

  const system =
    "You help a user refine the SOURCE material for a short-form Korean news video, BEFORE the script is " +
    "written. You are given the current title and body (Korean). Apply the user's request — rewrite parts, " +
    "emphasize a section, adjust tone/length, integrate or combine facts from multiple sources, fix errors — " +
    "and return the FULL updated material. Keep the body as ONE coherent Korean narrative (no markdown, no " +
    "bullet lists, no '소스1/2' labels). Preserve important facts and numbers unless asked to change them. " +
    "Aim for high-quality, engaging, accurate content. Also write a short Korean reply summarizing what changed. " +
    'Return ONLY JSON: {"reply":"...","title":"...","body":"..."}';

  const userMsg =
    `현재 소스 제목: ${material.title}\n\n현재 소스 본문:\n${material.body}\n\n요청: ${userMessage}`;

  const r = await client.messages.create({
    model: MODELS.opus,
    max_tokens: 8000,
    system,
    messages: [{ role: "user", content: userMsg }],
  });

  const raw = textOf(r.content);

  const costUsd = anthropicCostUsd({
    inputTokens: r.usage.input_tokens,
    outputTokens: r.usage.output_tokens,
    cacheReadTokens: r.usage.cache_read_input_tokens ?? undefined,
    cacheWriteTokens: r.usage.cache_creation_input_tokens ?? undefined,
    model: MODELS.opus,
  });
  await recordCost({
    projectId,
    vendor: "anthropic",
    model: MODELS.opus,
    costUsd,
    meta: { kind: "source-chat" },
  }).catch(() => {});

  let parsed: { reply?: unknown; title?: unknown; body?: unknown } = {};
  try {
    const m = raw.match(/\{[\s\S]*\}/);
    parsed = JSON.parse(m ? m[0] : raw);
  } catch {
    /* 파싱 실패 → 기존 자료 유지, 원문을 답변으로 */
  }
  const title =
    typeof parsed.title === "string" && parsed.title.trim() ? parsed.title.trim() : material.title;
  const body =
    typeof parsed.body === "string" && parsed.body.trim() ? parsed.body.trim() : material.body;
  const reply =
    typeof parsed.reply === "string" && parsed.reply.trim()
      ? parsed.reply.trim()
      : "반영했어요. 본문을 확인해 주세요.";

  return { reply, material: { ...material, title, body }, costUsd };
}

// 2단계 스크립트 대화 — 씬 나레이션들을 대화로 수정한다(재작성·분할/병합·추가/삭제·
// 순서·톤/훅). 좋은 모델(opus). 현재 나레이션 목록을 넘기고, 갱신된 나레이션 배열 +
// 한국어 요약 답변을 돌려준다. 이미지 프롬프트·모션은 여기서 만들지 않는다(다음 단계).
export async function runScriptChat(args: {
  projectId: string;
  narrations: string[];
  userMessage: string;
}): Promise<{ reply: string; narrations: string[]; costUsd: number }> {
  const { projectId, narrations, userMessage } = args;
  const client = getAnthropic();

  const system =
    "You help a user refine the SCRIPT of a short-form Korean news video. The script is a list of scene " +
    "narrations (Korean, spoken). Apply the user's request — reword, shorten or expand, split or merge scenes, " +
    "add or remove a scene, reorder, sharpen the hook, adjust tone — and return the FULL updated list of scene " +
    "narrations. Each narration is natural Korean speech (one or two short sentences) that works for both " +
    "voiceover and on-screen subtitles. Keep 5-9 scenes unless the user asks otherwise. Do NOT write image " +
    "prompts or motion — narration only. Also write a short Korean reply summarizing what changed. " +
    'Return ONLY JSON: {"reply":"...","scenes":["나레이션1","나레이션2", ...]}';

  const userMsg =
    "현재 씬 나레이션:\n" +
    narrations.map((n, i) => `${i + 1}. ${n}`).join("\n") +
    `\n\n요청: ${userMessage}`;

  const r = await client.messages.create({
    model: MODELS.opus,
    max_tokens: 8000,
    system,
    messages: [{ role: "user", content: userMsg }],
  });

  const raw = textOf(r.content);
  const costUsd = anthropicCostUsd({
    inputTokens: r.usage.input_tokens,
    outputTokens: r.usage.output_tokens,
    cacheReadTokens: r.usage.cache_read_input_tokens ?? undefined,
    cacheWriteTokens: r.usage.cache_creation_input_tokens ?? undefined,
    model: MODELS.opus,
  });
  await recordCost({
    projectId,
    vendor: "anthropic",
    model: MODELS.opus,
    costUsd,
    meta: { kind: "script-chat" },
  }).catch(() => {});

  let parsed: { reply?: unknown; scenes?: unknown } = {};
  try {
    const m = raw.match(/\{[\s\S]*\}/);
    parsed = JSON.parse(m ? m[0] : raw);
  } catch {
    /* 파싱 실패 → 기존 유지 */
  }
  const nextList = Array.isArray(parsed.scenes)
    ? parsed.scenes.map((x) => (typeof x === "string" ? x.trim() : "")).filter(Boolean)
    : [];
  const next = nextList.length > 0 ? nextList : narrations;
  const reply =
    typeof parsed.reply === "string" && parsed.reply.trim()
      ? parsed.reply.trim()
      : "반영했어요. 씬을 확인해 주세요.";

  return { reply, narrations: next, costUsd };
}
